import React, { FC, ReactElement, ReactNode, useEffect, useState } from 'react';
import Head from 'next/head'

import styles from './Layout.module.css'
import Logo from 'components/Icons/Logo';
import Link from 'next/link';
import { Brightness1, Brightness6Rounded } from '@mui/icons-material';

enum Theme {
    Light = 'light',
    Dark = 'dark',
}
interface PropsType {
    children: ReactNode;
    title?: string;
}

const Layout: FC<PropsType> = ({ children, title = 'World Ranks' }): ReactElement => {
    const [theme, setTheme] = useState<string>(Theme.Light)

    useEffect(() => {
        document.documentElement.setAttribute('data-theme', localStorage.getItem('theme')!)

        setTheme(localStorage.getItem('theme')!)
    }, [])

    const switchTheme = (): void => {
        if (theme === Theme.Light) {
            saveTheme(Theme.Dark)
        } else {
            saveTheme(Theme.Light)
        }
    }

    const saveTheme = (newTheme: string): void => {
        setTheme(newTheme)
        localStorage.setItem('theme', newTheme)
        document.documentElement.setAttribute('data-theme', newTheme)
    }

    return (
        <>
            <div className={ styles.container }>
                <Head>
                    <title>{ title }</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <header className={ styles.header }>
                    <Link href='/'><a className={ styles.logo }><Logo /></a></Link>
                    <button className={ styles.theme_switcher } onClick={ switchTheme }>
                        <Brightness6Rounded />
                    </button>
                </header>

                <main className={ styles.main }>{ children }</main>

                <footer className={ styles.footer }>
                    Andrei Tolstoi by devchallenges
                </footer>
            </div>
        </>
    );
}

export default Layout;
